#!/bin/bash

if [ -z $(which docker) ]; then
  echo "Docker is not installed. Please take the time to install Docker from https://www.docker.com/ before installing coast."
  exit 1
fi

NAME="coast"
SOURCE_URL="https://raw.github.com/simon-ohara/${NAME}/master/bin/${NAME}"
INSTALL_PATH=$HOME/bin
BINARY=$INSTALL_PATH/$NAME
PLATFORM=$(uname)

case $PLATFORM in
  Darwin)
   CONFIG=".bash_profile"
   ;;
  Linux)
   CONFIG=".bashrc"
   ;;
 *)
   CONFIG="config"
   ;;
esac

mkdir $INSTALL_PATH
# check PATH for INSTALL_PATH?
if [[ ! $PATH = *"$INSTALL_PATH"* ]]; then
  echo "Adding $INSTALL_PATH to PATH"
  echo "export PATH=\"$INSTALL_PATH:\$PATH\"" >> $HOME/$CONFIG
  export PATH=$INSTALL_PATH:$PATH
fi
wget $SOURCE_URL --output-document=$BINARY
chmod +x $BINARY
