#!/bin/bash

# check for docker?
NAME="coast"
SOURCE_URL="https://raw.github.com/simon-ohara/${NAME}/master/${NAME}"
INSTALL_PATH="${HOME}/bin"

mkdir $INSTALL_PATH
# check PATH for INSTALL_PATH?
export PATH="$INSTALL_PATH:$PATH"
echo "PATH=$INSTALL_PATH:$PATH" >> $HOME/.bash_profile
wget $SOURCE_URL --directory-prefix $INSTALL_PATH
chmod +x $INSTALL_PATH/$NAME
